---
title: Services
description: Disable Services
privilege: TrustedInstaller 
actions:
  - !service: {name: 'AxInstSV', operation: change, startup: 4}
  - !service: {name: 'BcastDVRUserService_389fd', operation: change, startup: 4}
  - !service: {name: 'BDESVC', operation: change, startup: 4}
  - !service: {name: 'Beep', operation: change, startup: 4}
  - !service: {name: 'BluetoothUserService', operation: change, startup: 4}
  - !service: {name: 'BthAvctpSvc', operation: change, startup: 4}
  - !service: {name: 'bthserv', operation: change, startup: 4}
  - !service: {name: 'CDPUserSvc', operation: change, startup: 4}
  - !service: {name: 'CldFlt', operation: change, startup: 4}
  - !service: {name: 'CscService', operation: change, startup: 4}
  - !service: {name: 'diagsvc', operation: change, startup: 4}
  - !service: {name: 'DiagTrack', operation: change, startup: 4}
  - !service: {name: 'dmwappushservice', operation: change, startup: 4}
  - !service: {name: 'DoSvc', operation: change, startup: 4}
  - !service: {name: 'dps', operation: change, startup: 4}
  - !service: {name: 'dusmsvc', operation: change, startup: 4}
  - !service: {name: 'Fax', operation: change, startup: 4}
  - !service: {name: 'FrameServer', operation: change, startup: 4}
  - !service: {name: 'FrameServerMonitor', operation: change, startup: 4}
  - !service: {name: 'GpuEnergyDrv', operation: change, startup: 4}
  - !service: {name: 'icssvc', operation: change, startup: 4}
  - !service: {name: 'kdnic', operation: change, startup: 4}
  - !service: {name: 'lfsvc', operation: change, startup: 4}
  - !service: {name: 'lltdsvc', operation: change, startup: 4}
  - !service: {name: 'MapsBroker', operation: change, startup: 4}
  - !service: {name: 'NetBT', operation: change, startup: 4}
  - !service: {name: 'NetTcpPortSharing', operation: change, startup: 4}
  - !service: {name: 'onesyncsvc', operation: change, startup: 4}
  - !service: {name: 'pcasvc', operation: change, startup: 4}
  - !service: {name: 'PhoneSvc', operation: change, startup: 4}
  - !service: {name: 'PrintNotify', operation: change, startup: 4}
  - !service: {name: 'PrintWorkflowUserSv', operation: change, startup: 4}
  - !service: {name: 'QWAVE', operation: change, startup: 4}
  - !service: {name: 'RemoteAccess', operation: change, startup: 4}
  - !service: {name: 'RetailDemo', operation: change, startup: 4}
  - !service: {name: 'ScDeviceEnum', operation: change, startup: 4}
  - !service: {name: 'SEMgrSvc', operation: change, startup: 4}
  - !service: {name: 'SensorDataService', operation: change, startup: 4}
  - !service: {name: 'SensorService', operation: change, startup: 4}
  - !service: {name: 'SensrSvc', operation: change, startup: 4}
  - !service: {name: 'SharedAccess', operation: change, startup: 4}
  - !service: {name: 'ShellHWDetection', operation: change, startup: 4}
  - !service: {name: 'Spooler', operation: change, startup: 4}
  - !service: {name: 'SSDPSRV', operation: change, startup: 4}
  - !service: {name: 'stisvc', operation: change, startup: 4}
  - !service: {name: 'sysmain', operation: change, startup: 4}
  - !service: {name: 'TrkWks', operation: change, startup: 4}
  - !service: {name: 'TroubleshootingSvc', operation: change, startup: 4}
  - !service: {name: 'tzautoupdates', operation: change, startup: 4}
  - !service: {name: 'UevAgentService', operation: change, startup: 4}
  - !service: {name: 'upnphost', operation: change, startup: 4}
  - !service: {name: 'UserDataSvc', operation: change, startup: 4}
  - !service: {name: 'WdiServiceHost', operation: change, startup: 4}
  - !service: {name: 'WdiSystemHost', operation: change, startup: 4}
  - !service: {name: 'wercplsupport', operation: change, startup: 4}
  - !service: {name: 'WerSvc', operation: change, startup: 4}
  - !service: {name: 'WiaRpc', operation: change, startup: 4}
  - !service: {name: 'wisvc', operation: change, startup: 4}
  - !service: {name: 'WMPNetworkSvc', operation: change, startup: 4}
  - !service: {name: 'WpcMonSvc', operation: change, startup: 4}
